import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { authApi } from '../services/auth'
import { assetsApi } from '../services/assets'
import { generationApi } from '../services/generation'
import { projectsApi } from '../services/projects'
import { renderApi } from '../services/render'
import { transcriptsApi } from '../services/transcripts'
import { componentsApi } from '../services/components'
import { useAuthStore } from '../store/authStore'
import { RENDER_POLL_INTERVAL } from '../utils/constants'
import type { Asset, Render, RenderStatus, RenderStatusPayload, ValidationResult, GenerationResponse } from '../types/api'
import { isTerminalRenderStatus } from '../types/api'

export const useProjects = () => { const client = useQueryClient(); const list = useQuery({ queryKey: ['projects'], queryFn: projectsApi.list, enabled: Boolean(useAuthStore.getState().token) }); const create = useMutation({ mutationFn: ({ name, spec }: { name: string; spec?: Record<string, unknown> }) => projectsApi.create(name, spec), onSuccess: () => client.invalidateQueries({ queryKey: ['projects'] }) }); return { ...list, create } }
export const useProject = (id?: string) => { const client = useQueryClient(); const query = useQuery({ queryKey: ['project', id], queryFn: () => projectsApi.get(id!), enabled: Boolean(id) }); const update = useMutation({ mutationFn: (data: Partial<{ name: string; spec: Record<string, unknown> }>) => projectsApi.update(id!, data), onSuccess: () => client.invalidateQueries({ queryKey: ['project', id] }) }); const validate = useMutation({ mutationFn: (spec: Record<string, unknown>) => projectsApi.validate(id!, spec) }); return { ...query, update, validate } }
export const useAssets = (projectId?: string) => { const client = useQueryClient(); const token = useAuthStore((state) => state.token); const query = useQuery({ queryKey: ['assets', projectId], queryFn: () => assetsApi.list(projectId!), enabled: Boolean(token) && Boolean(projectId) }); const upload = useMutation({ mutationFn: ({ file, kind, projectId, onProgress }: { file: File; kind: Parameters<typeof assetsApi.upload>[1]; projectId: string; onProgress?: (progress: number) => void }) => assetsApi.upload(file, kind, projectId, onProgress), onSuccess: (asset) => { client.setQueryData<Asset[]>(['assets', projectId], (current) => current ? [asset, ...current.filter((item) => item.id !== asset.id)] : [asset]); void client.invalidateQueries({ queryKey: ['assets', projectId] }) } }); const remove = useMutation({ mutationFn: ({ id, projectId }: { id: string; projectId?: string }) => assetsApi.remove(id, projectId), onSuccess: () => client.invalidateQueries({ queryKey: ['assets', projectId] }) }); const shareUrl = useMutation({ mutationFn: assetsApi.shareUrl }); return { ...query, upload, remove, shareUrl } }
export const useAssetTranscripts = (assetId: string, projectId?: string, enabled = true) => { const client = useQueryClient(); const query = useQuery({ queryKey: ['transcripts', assetId, projectId], queryFn: () => transcriptsApi.listForAsset(assetId, projectId), enabled: Boolean(assetId) && enabled }); const transcribe = useMutation({ mutationFn: (params: { language?: string; projectId?: string }) => transcriptsApi.transcribe(assetId, params.language, params.projectId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['transcripts', assetId, projectId] }) } }); const importTranscript = useMutation({ mutationFn: (params: { transcript: unknown; projectId?: string }) => transcriptsApi.import(assetId, params.transcript, params.projectId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['transcripts', assetId, projectId] }) } }); return { ...query, transcribe, importTranscript } }
export const useComponents = (params?: { query?: string; filter?: 'all' | 'mine' | 'public' | 'project'; projectId?: string }) => useQuery({ queryKey: ['components', params], queryFn: () => componentsApi.search(params) })
export const useGeneration = (projectId?: string) => { const client = useQueryClient(); const generate = useMutation({ mutationFn: (payload: Parameters<typeof generationApi.generate>[1]) => generationApi.generate(projectId!, payload) }); const manualPrompt = useMutation({ mutationFn: (payload: Parameters<typeof generationApi.manualPrompt>[1]) => generationApi.manualPrompt(projectId!, payload) }); const manualSubmit = useMutation({ mutationFn: (payload: Parameters<typeof generationApi.manualSubmit>[1]) => generationApi.manualSubmit(projectId!, payload) }); return { generate, manualPrompt, manualSubmit } }
export const useRenders = (projectId?: string) => { const client = useQueryClient(); const query = useQuery({ queryKey: ['renders', projectId], queryFn: () => renderApi.list(projectId!), enabled: Boolean(projectId), refetchInterval: (current) => current.state.data?.some((render) => render.status === 'queued' || render.status === 'running') ? RENDER_POLL_INTERVAL : false }); const create = useMutation({ mutationFn: () => renderApi.create(projectId!), onSuccess: () => client.invalidateQueries({ queryKey: ['renders', projectId] }) }); return { ...query, create } }
export const pollIntervalForRenderStatus = (status: RenderStatus | undefined): number | false =>
  !status || isTerminalRenderStatus(status) ? false : RENDER_POLL_INTERVAL
export const useSceneRenders = (sceneId?: string) => { const client = useQueryClient(); const query = useQuery({ queryKey: ['scene-renders', sceneId], queryFn: () => renderApi.listSceneRenders(sceneId!), enabled: Boolean(sceneId), refetchInterval: (current) => current.state.data?.some((render) => !isTerminalRenderStatus(render.status)) ? RENDER_POLL_INTERVAL : false }); const create = useMutation({ mutationFn: (clientKey?: string) => renderApi.createSceneRender(sceneId!, clientKey), onSuccess: (render) => { client.setQueryData<Render[]>(['scene-renders', sceneId], (current) => current ? [render, ...current.filter((item) => item.id !== render.id)] : [render]); void client.invalidateQueries({ queryKey: ['scene-renders', sceneId] }) } }); const cancel = useMutation({ mutationFn: (renderId: string) => renderApi.cancel(renderId), onSuccess: () => client.invalidateQueries({ queryKey: ['scene-renders', sceneId] }) }); return { ...query, create, cancel } }
export const useRenderStatus = (renderId?: string, enabled = true) => useQuery({ queryKey: ['render-status', renderId], queryFn: () => renderApi.getStatus(renderId!), enabled: Boolean(renderId) && enabled, refetchInterval: (current) => pollIntervalForRenderStatus((current.state.data as RenderStatusPayload | undefined)?.status) })
export const useAuth = () => { const setAuth = useAuthStore((state) => state.setAuth); const login = useMutation({ mutationFn: authApi.login, onSuccess: ({ user, token }) => setAuth(user, token) }); const register = useMutation({ mutationFn: authApi.register, onSuccess: ({ user, token }) => setAuth(user, token) }); return { login, register } }
