import { useMemo, useState } from 'react'
import { Activity, Film, Plus, Search, Sparkles, Zap } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Navbar } from '../components/layout/Navbar'
import { LoadingSpinner } from '../components/common/LoadingSpinner'
import { ErrorAlert } from '../components/common/ErrorAlert'
import { NewProjectDialog } from '../components/projects/NewProjectDialog'
import { ProjectCard } from '../components/projects/ProjectCard'
import { useProjects } from '../hooks/useApi'
import { getApiError } from '../services/api'

export function DashboardPage() { const navigate = useNavigate(); const { data: projects = [], isLoading, error } = useProjects(); const [query, setQuery] = useState(''); const [dialog, setDialog] = useState(false); const filtered = useMemo(() => projects.filter((project) => project.name.toLowerCase().includes(query.toLowerCase())), [projects, query]); return <div className="app"><Navbar /><main className="dashboard-page"><div className="dashboard-heading"><div><p className="eyebrow">Your workspace</p><h1>Make something clear<span className="blue-dot">.</span></h1><p className="lede">Turn ideas into clear, beautiful stories.</p></div><button className="button primary new-project" onClick={() => setDialog(true)}><Plus size={18} />New project</button></div><section className="stats-row"><Stat icon={<Film size={18} />} tone="blue" label="Projects" value={projects.length.toString()} note="in your workspace" /><Stat icon={<Zap size={18} />} tone="orange" label="Minutes created" value="—" note="render to see usage" /><Stat icon={<Activity size={18} />} tone="green" label="Renders this week" value="—" note="live from your queue" /></section><div className="section-heading"><div><h2>Recent projects</h2><p>Pick up where you left off.</p></div><div className="list-tools"><div className="search-box"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects" /></div></div></div><ErrorAlert message={error ? getApiError(error, 'Could not load projects') : undefined} />{isLoading ? <div className="loading-panel"><LoadingSpinner /></div> : <div className="project-grid">{filtered.map((project) => <ProjectCard key={project.id} project={project} onOpen={() => navigate(`/projects/${project.id}`)} />)}<button className="new-card" onClick={() => setDialog(true)}><div className="new-card-icon"><Plus size={20} /></div><strong>Create a new project</strong><span>Start with a blank canvas</span></button></div>}<div className="bottom-insight"><Sparkles size={18} /><div><strong>Make your next idea visual</strong><span>Upload a voiceover or start with a prompt. Framewell will take care of the rest.</span></div></div></main>{dialog && <NewProjectDialog onClose={() => setDialog(false)} onCreated={(id) => navigate(`/projects/${id}`)} />}</div> }
function Stat({ icon, tone, label, value, note }: { icon: React.ReactNode; tone: string; label: string; value: string; note: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong></div><small>{note}</small></div> }
